title: Yitong Shan 
logo: "/images/profilepic.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="yitonsh@cs.washington.edu">Email</a> 
  <br><br>
  Resume
  <br><br>
  <a href="https://www.linkedin.com/in/yitong-shan-a2a72b1a9/">LinkedIn</a> 
  <br><br>
  <a href="https://github.com/evasy">GitHub</a> 
  
theme: jekyll-theme-minimal
